import { z } from "zod/v4";
import {
  dtaEvent,
  dtaInstitutionDetail,
  dtaInstitutionPreview,
  dtaLocation,
  dtaMap,
  dtaObjectDetail,
  dtaObjectPreview,
  dtaPage,
  dtaPersonDetail,
  dtaPersonPreview,
  dtaPracticeDetail,
  dtaPracticePreview,
  dtaSnippet,
} from "@/lib/schemas/dta";
import {
  schoolApplyEntryDetail,
  schoolApplyEntryPreview,
  schoolEventPreview,
  schoolFacilityPreview,
  schoolProgrammeDetail,
  schoolProgrammePreview,
  schoolSnippet,
  schoolUnitDetail,
  schoolUnitPreview,
  schoolVisitingSchoolDetail,
  schoolVisitingSchoolPreview,
  schoolVisitingSchoolSnippet,
} from "@/lib/schemas/school";
import {
  document,
  file,
  getManyRes,
  getOneRes,
  img,
  media,
  pagination,
  seo,
  video,
} from "@/lib/schemas/shared";

// When importing files, use named imports for treeshaking

export const schemas = {
  document,
  video,
  file,
  img,
  media,
  seo,
  pagination,
  getOneRes,
  getManyRes,
  dtaPersonPreview,
  dtaPersonDetail,
  dtaPracticePreview,
  dtaPracticeDetail,
  dtaInstitutionPreview,
  dtaInstitutionDetail,
  dtaObjectPreview,
  dtaObjectDetail,
  dtaLocation,
  dtaPage,
  dtaSnippet,
  dtaMap,
  dtaEvent,
  schoolEventPreview,
  schoolFacilityPreview,
  schoolProgrammePreview,
  schoolProgrammeDetail,
  schoolUnitPreview,
  schoolUnitDetail,
  schoolVisitingSchoolSnippet,
  schoolVisitingSchoolPreview,
  schoolVisitingSchoolDetail,
  schoolSnippet,
  schoolApplyEntryPreview,
  schoolApplyEntryDetail,
};

export type Schema<
  Key extends Exclude<keyof typeof schemas, "getOneRes" | "getManyRes">,
> = z.infer<(typeof schemas)[Key]>;
