import type { Meta, StoryObj } from "@storybook/nextjs-vite";
import { DTAFilterMultiSelect } from "@/components/DTA/components/Filter/DTAFilterMultiSelect";

const mockAlphabetFilters = [
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "G",
  "H",
  "I",
  "J",
  "K",
  "L",
  "M",
  "N",
  "O",
  "P",
  "Q",
  "R",
  "S",
  "T",
  "U",
  "V",
  "W",
  "X",
  "Y",
  "Z",
];
const mockBirthPlaceFilters = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Angola",
  "Argentina",
  "Armenia",
  "Azerbaijan",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belize",
  "Bhutan",
  "Bolivia",
  "Botswana",
  "Brazil",
  "Bulgaria",
  "Cambodia",
  "Chile",
  "China",
  "Colombia",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Czech Republic",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Eritrea",
  "Estonia",
  "Ethiopia",
  "Fiji",
  "Georgia",
  "Ghana",
  "Guatemala",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Jamaica",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Laos",
  "Latvia",
  "Lebanon",
  "Liberia",
  "Libya",
  "Lithuania",
  "Malaysia",
  "Maldives",
  "Mexico",
  "Micronesia",
  "Mongolia",
  "Myanmar",
  "Namibia",
  "Nepal",
  "Nicaragua",
  "Oman",
  "Pakistan",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Romania",
  "Rwanda",
  "Samoa",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Sri Lanka",
  "Sudan",
  "Syria",
  "Taiwan",
  "Tanzania",
  "Thailand",
  "Tunisia",
  "Turkey",
  "Uganda",
  "Ukraine",
  "United Kingdom",
  "Uruguay",
  "Uzbekistan",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];
const mockCountryFilters = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Angola",
  "Argentina",
  "Armenia",
  "Azerbaijan",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belize",
  "Bhutan",
  "Bolivia",
  "Botswana",
  "Brazil",
  "Bulgaria",
  "Cambodia",
  "Chile",
  "China",
  "Colombia",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Czech Republic",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Eritrea",
  "Estonia",
  "Ethiopia",
  "Fiji",
  "Georgia",
  "Ghana",
  "Guatemala",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Jamaica",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Laos",
  "Latvia",
  "Lebanon",
  "Liberia",
  "Libya",
  "Lithuania",
  "Malaysia",
  "Maldives",
  "Mexico",
  "Micronesia",
  "Mongolia",
  "Myanmar",
  "Namibia",
  "Nepal",
  "Nicaragua",
  "Oman",
  "Pakistan",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Romania",
  "Rwanda",
  "Samoa",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Sri Lanka",
  "Sudan",
  "Syria",
  "Taiwan",
  "Tanzania",
  "Thailand",
  "Tunisia",
  "Turkey",
  "Uganda",
  "Ukraine",
  "United Kingdom",
  "Uruguay",
  "Uzbekistan",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];
const mockInstitutionTypeFilters = [
  "Universities",
  "Governmental Bodies",
  "Non-Governmental Bodies",
  "Transnational Organizations",
];
const mockYearFilters = [
  "1950",
  "1951",
  "1952",
  "1953",
  "1954",
  "1955",
  "1956",
  "1957",
  "1978",
  "1959",
  "1960",
  "1961",
  "1962",
  "1963",
  "1964",
  "1965",
  "1966",
  "1967",
  "1968",
  "1969",
  "1970",
  "1971",
  "1972",
  "1973",
  "1974",
  "1975",
  "Unknown",
];
const mockYearOfStudyFilters = [
  "1950",
  "1951",
  "1952",
  "1953",
  "1954",
  "1955",
  "1956",
  "1957",
  "1978",
  "1959",
  "1960",
  "1961",
  "1962",
  "1963",
  "1964",
  "1965",
  "1966",
  "1967",
  "1968",
  "1969",
  "1970",
  "1971",
  "1972",
  "1973",
  "1974",
  "1975",
  "Unknown",
];

const meta = {
  title: "DTA/03 Components/Filter/Multi-Select Filter",
  component: DTAFilterMultiSelect,
  parameters: {
    docs: {
      description: {
        component: " ",
      },
    },
  },
  argTypes: {
    className: {
      table: { disable: true },
    },
    filters: {
      table: { disable: true },
    },
    multiFilterType: {
      table: { disable: true },
    },
  },
} satisfies Meta<typeof DTAFilterMultiSelect>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Alphabet: Story = {
  args: {
    colorTheme: "people",
    className: "px-[40px] pt-[30vh] w-[90vw]",
    multiFilterType: "alphabet",
    filters: mockAlphabetFilters,
    activeIndex: 0,
    index: 0,
    activeFilters: [],
    toggleFilter: () => {},
    clearFilters: () => {},
    setActiveIndex: () => {},
  },
  argTypes: {
    colorTheme: {
      control: "select",
      options: ["people", "institutions", "practices"],
    },
  },
  globals: {
    backgrounds: { value: "light" },
  },
};

export const BirthPlace: Story = {
  args: {
    colorTheme: "people",
    className: "px-[40px] pt-[30vh] w-[90vw]",
    multiFilterType: "birthPlace",
    filters: mockBirthPlaceFilters,
    activeIndex: 0,
    index: 0,
    activeFilters: [],
    toggleFilter: () => {},
    clearFilters: () => {},
    setActiveIndex: () => {},
  },
  argTypes: {
    colorTheme: {
      table: { disable: true },
    },
  },
  globals: {
    backgrounds: { value: "light" },
  },
};

export const Country: Story = {
  args: {
    colorTheme: "people",
    className: "px-[40px] pt-[30vh]",
    multiFilterType: "country",
    filters: mockCountryFilters,
    activeIndex: 0,
    index: 0,
    activeFilters: [],
    toggleFilter: () => {},
    clearFilters: () => {},
    setActiveIndex: () => {},
  },
  argTypes: {
    colorTheme: {
      control: "select",
      options: ["institutions", "practices"],
    },
  },
  globals: {
    backgrounds: { value: "light" },
  },
};

export const InstitutionType: Story = {
  args: {
    colorTheme: "people",
    className: "px-[40px] pt-[30vh]",
    multiFilterType: "institutionType",
    filters: mockInstitutionTypeFilters,
    activeIndex: 0,
    index: 0,
    activeFilters: [[]],
    toggleFilter: () => {},
    clearFilters: () => {},
    setActiveIndex: () => {},
  },
  argTypes: {
    colorTheme: {
      table: { disable: true },
    },
  },
  globals: {
    backgrounds: { value: "light" },
  },
};

export const Year: Story = {
  args: {
    colorTheme: "people",
    className: "px-[40px] pt-[30vh]",
    multiFilterType: "year",
    filters: mockYearFilters,
    activeIndex: 0,
    index: 0,
    activeFilters: [[]],
    toggleFilter: () => {},
    clearFilters: () => {},
    setActiveIndex: () => {},
  },
  argTypes: {
    colorTheme: {
      control: "select",
      options: ["institutions", "practices"],
    },
  },
  globals: {
    backgrounds: { value: "light" },
  },
};

export const YearOfStudy: Story = {
  args: {
    colorTheme: "people",
    className: "px-[40px] pt-[30vh]",
    multiFilterType: "yearOfStudy",
    filters: mockYearOfStudyFilters,
    activeIndex: 0,
    index: 0,
    activeFilters: [[]],
    toggleFilter: () => {},
    clearFilters: () => {},
    setActiveIndex: () => {},
  },
  argTypes: {
    colorTheme: {
      table: { disable: true },
    },
  },
  globals: {
    backgrounds: { value: "light" },
  },
};
